version: "2"

services:

  rng:
    image: docker.io/library/rng:0.0.1-SNAPSHOT
    ports:
    - "8080:8080"

  hasher:
    image: docker.io/library/hasher:0.0.1-SNAPSHOT
    ports:
    - "8090:8080"

  webui:
    build: webui
    ports:
    - "80:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis:6.2.1

  worker:
    build: worker
