{
 "title": "Demo Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num. Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"worker\"})"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(redis_requests_number{app=\"worker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{app=\"worker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Mo" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{app=\"worker\"} /1024 /1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(redis_requests_number{app=\"worker\"}[1m]))"
    }
   ]
  },
  { "title": "Random Number Generator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Num. Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"rng\"})"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(rng_requests_number{app=\"worker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"demo\", container=\"rng\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Mo" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", namespace=\"demo\", container=\"rng\"} /1024 /1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(rng_requests_number{app=\"worker\"}[1m]))"
    }
   ]
  },
  { "title": "Hasher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Num. Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"hasher\"})"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(hasher_requests_number{app=\"worker\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"demo\", container=\"hasher\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Mo" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", namespace=\"demo\", container=\"hasher\"} /1024 /1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(hasher_requests_number{app=\"worker\"}[1m]))"
    }
   ]
  }
 ]
}